### ISSUE TITLE
TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by larryosborn** [karlg100/frigidaire#5]
I'm trying to install the module for homebridge and it's has this uncaught exception.

```
TypeError: Cannot read property 'attributes' of undefined
    at /homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:439:58
    at Request._callback (/homebridge/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:285:14)
    at Request.self.callback (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-frigidaire/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
```

**Comment by karlg100** [comment]
are you still having this issue with the 2.0.0 update?

**Comment by karlg100** [comment]
I've retooled with 2.1 a good chunk of this lib.  hopefully this is fixed.

**Comment by karlg100** [comment]
Please update to latest version via npm.  Please reopen issue if still a problem.
