### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by amaisano** [karlg100/frigidaire#7]
```
[6/5/2021, 3:03:47 PM] SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/frigidaire/lib/frigidaire.js:236:42)
    at self.callback (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-frigidaire/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[6/5/2021, 3:03:47 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by karlg100** [comment]
Think I found the issue.  one of the request.get() calls was not trapping errors.  Added a trap in my checked out version and will push an update if corrected.

**Comment by karlg100** [comment]
found a second issue, related to this one.  https://github.com/karlg100/frigidaire/commit/7b4199f276e05433f5a9c8c9e34f35c065dc165f

**Comment by karlg100** [comment]
Please update to latest version via npm.  Please reopen issue if still a problem.
